# Generated by Django 3.0.6 on 2020-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(blank=True, upload_to='image/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
